version: "3.5"
services:
  db:
    image: postgres:9.4
    ports:
      - 5432
  hello-graphql:
    build:
      context: .
      shm_size: '256m'
    security_opt:
      - seccomp:unconfined
    depends_on:
      - db
    command: sh -c "./hello-graphql.sh"
    volumes:
        - .:/hello-graphql
    links:
      - db:db
    environment:
      PGHOST: 'db'
      PGUSER: 'postgres'
      PGDATABASE: 'hello-graphql'
      PGPORT: 5432
      NETLIFY_ACCESS_TOKEN: ${NETLIFY_ACCESS_TOKEN}
      HEROKU_EMAIL: mayorga.julian@gmail.com
      HEROKU_TOKEN: ${HEROKU_TOKEN}